name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: sudo apt-get install --yes git jq
    - run: yarn install
    - run: yarn build

    - name: Test
      run: yarn test

    - name: Publish dev build
      run: .github/scripts/publish-dev-build '${{ secrets.GITHUB_TOKEN }}'
      if: ${{ github.event_name == 'push' }}
